# Generated by Django 2.1.3 on 2018-11-21 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curry_order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('curry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curry_order.Curry')),
            ],
        ),
    ]
