# Generated by Django 2.1.2 on 2018-11-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curry_order', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_name',
            field=models.CharField(default='test_user', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
