# Generated by Django 2.1.2 on 2018-11-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curry_order', '0003_order_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='curry',
            name='image',
            field=models.FilePathField(default=''),
            preserve_default=False,
        ),
    ]
