# Generated by Django 2.1.2 on 2018-11-25 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curry_order', '0005_orderentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderentry',
            old_name='event',
            new_name='group',
        ),
        migrations.AddField(
            model_name='order',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='curry_order.OrderEntry'),
            preserve_default=False,
        ),
    ]
